### PR TITLE
Fixed Navbar Layout & Navigation System

### LINKED ISSUE #105: Fixed Navbar Layout & Navigation System
Implement fixed navbar layout component with proper navigation for settings and home.

## Changes
- Create new Layout component with fixed header and navigation
- Integrate layout in main page.tsx and settings page
- Add Settings/Home navigation with proper routing
- Responsive navigation with mobile support

## Features
- Fixed header with backdrop blur
- Settings ⇄ Home navigation toggle
- Portfolio value display
- Wallet connection integration
- Responsive design for mobile

### PR DESCRIPTION
**Pull request by elastikchainn**
Closes #105

Implement fixed navbar layout component with proper navigation system.

## Changes
- Added new Layout component with fixed header and backdrop blur
- Integrated Layout in main page.tsx and settings page
- Added Settings ⇄ Home navigation toggle with icons
- Responsive design with mobile-first approach

## Features  
- Fixed positioned header with proper z-index
- Navigation icons (Settings/Home) with conditional display
- Portfolio value integration
- Wallet connection component integration
- Proper spacing and visual hierarchy
- Mobile responsive navigation

## UI Improvements
- Consistent header across all pages
- Professional gradient backgrounds
- Smooth transitions and hover effects

### CODE REVIEW

File: yetify-frontend/src/components/Layout.tsx [hunk 1]
```diff
@@ -0,0 +1,98 @@
...
+              <span>Multi-Chain Support</span>
+              <span>•</span>
+              <span>Secure TEE Execution</span>
+            </div>
+          </div>
+        </div>
+      </footer>
+    </div>
+  );
+}
```
Comment (medamineid) [inline yetify-frontend/src/components/Layout.tsx:98]: add nav bar to layout

File: yetify-frontend/src/app/page.tsx [hunk 2]
```diff
@@ -71,28 +37,9 @@ export default function Home() {
...
-              <span>•</span>
-              <span>Secure TEE Execution</span>
-            </div>
-          </div>
-        </div>
-      </footer>
-    </div>
+      </div>
+    </Layout>
   );
```
Comment (medamineid) [inline yetify-frontend/src/app/page.tsx:44]: removed fixed code and add layout

**Review by medamineid — COMMENTED** [review]
added layout
