### PR TITLE
Fix TypeScript Strategy Action Types

### LINKED ISSUE #117: Fix Missing Strategy Action Types
Add 'swap' and 'withdraw' action types to fix TypeScript compilation errors.

Files: api-responses.ts, schemas/index.ts

### PR DESCRIPTION
**Pull request by medamineid**
Add missing 'swap' and 'withdraw' action types to resolve compilation errors.

Closes #117

### CODE REVIEW

File: yetify-backend/src/graphql/schemas/index.ts [hunk 1]
```diff
@@ -339,6 +339,8 @@ export const typeDefs = gql`
     PROVIDE_LIQUIDITY
     LEVERAGE
     BRIDGE
+    SWAP
```
Comment (medamineid) [inline yetify-backend/src/graphql/schemas/index.ts:342]: fixed ts error

File: yetify-backend/src/types/api-responses.ts [hunk 2]
```diff
@@ -123,7 +123,7 @@ export interface Strategy {
 }
 
 export interface StrategyStep {
-  action: 'deposit' | 'stake' | 'yield_farm' | 'provide_liquidity' | 'leverage' | 'bridge';
+  action: 'deposit' | 'stake' | 'yield_farm' | 'provide_liquidity' | 'leverage' | 'bridge' | 'swap' | 'withdraw';
```
Comment (medamineid) [inline yetify-backend/src/types/api-responses.ts:126]: fixed ts error

**Review by medamineid — COMMENTED** [review]
fixed
